const express = require("express");
const bcrypt = require("bcryptjs");
const User = require("../models/userModel");
const generateToken = require("../token.js");
const protect = require("../middleware/authMiddleware.js");

const userRouter = express.Router();

//Sign Up
userRouter.post("/signup", async (req, res) => {
  const newUser = new User({
    name: req.body.name,
    username: req.body.username,
    email: req.body.email,
    password: bcrypt.hashSync(req.body.password, 10),
    dictionary: [
      {
        word: "shrive",
        partOfSpeech: "verb",
        origin: "Old English",
        definition: "to free from guilt",
      },
      {
        word: "wreak",
        partOfSpeech: "verb",
        origin: "Old English",
        definition: "bring about, cause",
      },
    ],
    categories: [
      {
        name: "animals",
        words: [
          "Aardvark",
          "Aardwolf",
          "Albatross",
          "Alligator",
          "Alpaca",
          "American buffalo",
          "Anaconda",
          "Angelfish",
          "Anglerfish",
          "Ant",
          "Anteater",
          "Antelope",
          "Antlion",
          "Ape",
          "Arctic Fox",
          "Armadillo",
          "Arrow crab",
          "Asp",
          "Baboon",
          "Badger",
          "Bald eagle",
          "Bandicoot",
          "Barnacle",
          "Barracuda",
          "Bass",
          "Bat",
          "Beaked whale",
          "Bear",
          "Beaver",
          "Bedbug",
          "Bee",
          "Beetle",
          "Bird",
          "list",
          "Bison",
          "Blackbird",
          "Black widow spider",
          "Blue bird",
          "Blue jay",
          "Blue whale",
          "Boa",
          "Boar",
          "Bobcat",
          "Bobolink",
          "Bonobo",
          "Booby",
          "Box jellyfish",
          "Bug",
          "Butterfly",
          "Buzzard",
          "Camel",
          "Cape buffalo",
          "Capybara",
          "Cardinal",
          "Caribou",
          "Carp",
          "Cat",
          "Catshark",
          "Caterpillar",
          "Catfish",
          "Centipede",
          "Chameleon",
          "Cheetah",
          "Chickadee",
          "Chicken",
          "Chimpanzee",
          "Chinchilla",
          "Chipmunk",
          "Clam",
          "Clownfish",
          "Cobra",
          "Cockroach",
          "Cod",
          "Condor",
          "Cougar",
          "Cow",
          "Coyote",
          "Crab",
          "Crane",
          "Crawdad",
          "Crayfish",
          "Cricket",
          "Crocodile",
          "Crow",
          "Cuckoo",
          "Cicada",
          "Damselfly",
          "Deer",
          "Dingo",
          "Dinosaur",
          "Dog",
          "Dolphin",
          "Donkey",
          "Dormouse",
          "Dove",
          "Dragonfly",
          "Dragon",
          "Duck",
          "Dung beetle",
          "Eagle",
          "Earthworm",
          "Earwig",
          "Echidna",
          "Eel",
          "Egret",
          "Elephant",
          "Elephant seal",
          "Elk",
          "Emu",
          "Ermine",
          "Falcon",
          "Ferret",
          "Finch",
          "Firefly",
          "Fish",
          "Flamingo",
          "Flea",
          "Fly",
          "Fowl",
          "Fox",
          "Frog",
          "Fruit bat",
          "Gazelle",
          "Gecko",
          "Gerbil",
          "Gibbon",
          "Gila monster",
          "Giraffe",
          "Goat",
          "Goldfish",
          "Goose",
          "Gopher",
          "Gorilla",
          "Grasshopper",
          "Great white shark",
          "Grizzly bear",
          "Grouse",
          "Guan",
          "Guanaco",
          "Guineafowl",
          "Guinea pig",
          "Gull",
          "Guppy",
          "Haddock",
          "Halibut",
          "Hammerhead shark",
          "Hamster",
          "Hare",
          "Harrier",
          "Hawk",
          "Hedgehog",
          "Hermit crab",
          "Heron",
          "Herring",
          "Hippopotamus",
          "Hookworm",
          "Hornet",
          "Horse",
          "Hummingbird",
          "Humpback whale",
          "Hyena",
          "Iguana",
          "Impala",
          "Jackal",
          "Jaguar",
          "Jay",
          "Jellyfish",
          "Kangaroo",
          "Kingfisher",
          "Koala",
          "Koi",
          "Komodo dragon",
          "Krill",
          "Ladybug",
          "Lamprey",
          "Lark",
          "Leech",
          "Lemming",
          "Lemur",
          "Leopard",
          "Leopon",
          "Limpet",
          "Lion",
          "Lizard",
          "Llama",
          "Lobster",
          "Locust",
          "Loon",
          "Louse",
          "Lungfish",
          "Lynx",
          "Macaw",
          "Mackerel",
          "Magpie",
          "Mammal",
          "Manatee",
          "Mandrill",
          "Manta ray",
          "Marlin",
          "Marmoset",
          "Marmot",
          "Marsupial",
          "Marten",
          "Meadowlark",
          "Meerkat",
          "Mink",
          "Minnow",
          "Mite",
          "Mockingbird",
          "Mole",
          "Mollusk",
          "Mongoose",
          "Monitor lizard",
          "Monkey",
          "Moose",
          "Mosquito",
          "Moth",
          "Mouse",
          "Mule",
          "Muskox",
          "Narwhal",
          "Newt",
          "Nightingale",
          "Ocelot",
          "Octopus",
          "Opossum",
          "Orangutan",
          "Orca",
          "Ostrich",
          "Otter",
          "Owl",
          "Ox",
          "Panda",
          "Panther",
          "Parakeet",
          "Parrot",
          "Parrotfish",
          "Partridge",
          "Peacock",
          "Peafowl",
          "Pelican",
          "Penguin",
          "Perch",
          "Peregrine falcon",
          "Pheasant",
          "Pig",
          "Pigeon",
          "list",
          "Pike",
          "Pilot whale",
          "Pinniped",
          "Piranha",
          "Planarian",
          "Platypus",
          "Polar bear",
          "Pony",
          "Porcupine",
          "Porpoise",
          "Portuguese man o war",
          "Possum",
          "Prairie dog",
          "Prawn",
          "Praying mantis",
          "Primate",
          "Ptarmigan",
          "Puffin",
          "Puma",
          "Python",
          "Quail",
          "Quelea",
          "Quokka",
          "Rabbit",
          "Raccoon",
          "Rat",
          "Rattlesnake",
          "Raven",
          "Reindeer",
          "Reptile",
          "Rhinoceros",
          "Roadrunner",
          "Rook",
          "Rooster",
          "Roundworm",
          "Sailfish",
          "Salamander",
          "Salmon",
          "Sawfish",
          "Scallop",
          "Scorpion",
          "Seahorse",
          "Sea lion",
          "Sea slug",
          "Sea snail",
          "Shark",
          "Sheep",
          "Shrew",
          "Shrimp",
          "Silkworm",
          "Silverfish",
          "Skink",
          "Skunk",
          "Sloth",
          "Slug",
          "Smelt",
          "Snail",
          "Snake",
          "Snipe",
          "Snow leopard",
          "Sole",
          "Sparrow",
          "Sperm whale",
          "Spider",
          "Spider monkey",
          "Spoonbill",
          "Squid",
          "Squirrel",
          "Starfish",
          "Stingray",
          "Stoat",
          "Stork",
          "Sturgeon",
          "Swallow",
          "Swan",
          "Swift",
          "Swordfish",
          "Swordtail",
          "Tahr",
          "Takin",
          "Tapir",
          "Tarantula",
          "Tarsier",
          "Tasmanian devil",
          "Termite",
          "Tern",
          "Thrush",
          "Tick",
          "Tiger",
          "Tiglon",
          "Toad",
          "Tortoise",
          "Toucan",
          "Trout",
          "Tuna",
          "Turkey",
          "Turtle",
          "Urial",
          "Vampire bat",
          "Vicuna",
          "Viper",
          "Vole",
          "Vulture",
          "Wallaby",
          "Walrus",
          "Wasp",
          "Warbler",
          "Water buffalo",
          "Weasel",
          "Whale",
          "Whippet",
          "Whitefish",
          "Whooping crane",
          "Wildcat",
          "Wildebeest",
          "Wildfowl",
          "Wolf",
          "Wolverine",
          "Wombat",
          "Woodpecker",
          "Worm",
          "Wren",
          "Yak",
          "Yellow perch",
          "Zebra",
        ],
      },

      {
        name: "colors",
        words: [
          "alizarin",
          "amaranth",
          "amber",
          "amethyst",
          "apricot",
          "aqua",
          "aquamarine",
          "asparagus",
          "auburn",
          "azure",
          "beige",
          "bistre",
          "black",
          "blue",
          "brass",
          "bronze",
          "brown",
          "buff",
          "burgundy",
          "cardinal",
          "carmine",
          "celadon",
          "cerise",
          "cerulean",
          "champagne",
          "charcoal",
          "chartreuse",
          "chestnut",
          "chocolate",
          "cinnabar",
          "cinnamon",
          "cobalt",
          "copper",
          "coral",
          "corn",
          "cornflower",
          "cream",
          "crimson",
          "cyan",
          "dandelion",
          "denim",
          "ecru",
          "emerald",
          "eggplant",
          "firebrick",
          "flax",
          "fuchsia",
          "gamboge",
          "gold",
          "goldenrod",
          "green",
          "grey",
          "harlequin",
          "heliotrope",
          "indigo",
          "ivory",
          "jade",
          "khaki",
          "lavender",
          "lemon",
          "lilac",
          "lime",
          "linen",
          "magenta",
          "magnolia",
          "malachite",
          "maroon",
          "mauve",
          "mustard",
          "myrtle",
          "navy blue",
          "ochre",
          "olive",
          "olivine",
          "orange",
          "orchid",
          "peach",
          "pear",
          "periwinkle",
          "persimmon",
          "pink",
          "platinum",
          "plum",
          "puce",
          "pumpkin",
          "purple",
          "red",
          "rose",
          "ruby",
          "russet",
          "rust",
          "saffron",
          "salmon",
          "sangria",
          "sapphire",
          "scarlet",
          "seashell",
          "sepia",
          "silver",
          "sky blue",
          "smalt",
          "tan",
          "tangerine",
          "taupe",
          "teal",
          "tawny",
          "thistle",
          "turquoise",
          "ultramarine",
          "van dyke brown",
          "vermilion",
          "violet",
          "viridian",
          "white",
          "wisteria",
          "yellow",
        ],
      },

      {
        name: "fruits",
        words: [
          "apple",
          "apricot",
          "avocado",
          "banana",
          "bilberry",
          "blackberry",
          "blackcurrant",
          "blueberry",
          "boysenberry",
          "currant",
          "cherry",
          "cherimoya",
          "cloudberry",
          "coconut",
          "cranberry",
          "cucumber",
          "damson",
          "date",
          "dragonfruit",
          "durian",
          "elderberry",
          "feijoa",
          "fig",
          "goji berry",
          "gooseberry",
          "grape",
          "raisin",
          "grapefruit",
          "guava",
          "honeyberry",
          "huckleberry",
          "jabuticaba",
          "jackfruit",
          "jambul",
          "jujube",
          "juniper berry",
          "kiwano",
          "kiwifruit",
          "kumquat",
          "lemon",
          "lime",
          "loquat",
          "longan",
          "lychee",
          "mango",
          "mangosteen",
          "marionberry",
          "melon",
          "cantaloupe",
          "honeydew",
          "mulberry",
          "nectarine",
          "nance",
          "olive",
          "orange",
          "clementine",
          "mandarine",
          "tangerine",
          "papaya",
          "passionfruit",
          "peach",
          "pear",
          "persimmon",
          "physalis",
          "plantain",
          "plum",
          "prune",
          "pineapple",
          "plumcot",
          "pomegranate",
          "pomelo",
          "Quince",
          "qaspberry",
          "salmonberry",
          "rambutan",
          "redcurrant",
          "salal berry",
          "salak",
          "satsuma",
          "soursop",
          "star fruit",
          "solanum quitoense",
          "strawberry",
          "tamarillo",
          "tamarind",
          "ugli fruit",
          "watermelon",
          "yuzu",
        ],
      },
      {
        name: "countries",
        words: [
          "Afghanistan",
          "Albania",
          "Algeria",
          "Andorra",
          "Angola",
          "Antigua",
          "Argentina",
          "Armenia",
          "Australia",
          "Austria",
          "Azerbaijan",
          "Bahamas",
          "Bahrain",
          "Bangladesh",
          "Barbados",
          "Belarus",
          "Belgium",
          "Belize",
          "Benin",
          "Bhutan",
          "Bolivia",
          "Bosnia Herzegovina",
          "Botswana",
          "Brazil",
          "Brunei",
          "Bulgaria",
          "Burkina",
          "Burundi",
          "Cambodia",
          "Cameroon",
          "Canada",
          "Cape Verde",
          "Central African Republic",
          "Chad",
          "Chile",
          "China",
          "Colombia",
          "Comoros",
          "Congo",
          "Democratic Republic of Congo",
          "Costa Rica",
          "Croatia",
          "Cuba",
          "Cyprus",
          "Czechia",
          "Denmark",
          "Djibouti",
          "Dominica",
          "Dominican Republic",
          "East Timor",
          "Ecuador",
          "Egypt",
          "El Salvador",
          "Equatorial Guinea",
          "Eritrea",
          "Estonia",
          "Ethiopia",
          "Fiji",
          "Finland",
          "France",
          "Gabon",
          "Gambia",
          "Georgia",
          "Germany",
          "Ghana",
          "Greece",
          "Grenada",
          "Guatemala",
          "Guinea",
          "Guinea Bissau",
          "Guyana",
          "Haiti",
          "Honduras",
          "Hungary",
          "Iceland",
          "India",
          "Indonesia",
          "Iran",
          "Iraq",
          "Ireland",
          "Israel",
          "Italy",
          "Ivory Coast",
          "Jamaica",
          "Japan",
          "Jordan",
          "Kazakhstan",
          "Kenya",
          "Kiribati",
          "North Korea",
          "South Korea",
          "Kosovo",
          "Kuwait",
          "Kyrgyzstan",
          "Laos",
          "Latvia",
          "Lebanon",
          "Lesotho",
          "Liberia",
          "Libya",
          "Liechtenstein",
          "Lithuania",
          "Luxembourg",
          "Macedonia",
          "Madagascar",
          "Malawi",
          "Malaysia",
          "Maldives",
          "Mali",
          "Malta",
          "Marshall Islands",
          "Mauritania",
          "Mauritius",
          "Mexico",
          "Micronesia",
          "Moldova",
          "Monaco",
          "Mongolia",
          "Montenegro",
          "Morocco",
          "Mozambique",
          "Myanmar",
          "Namibia",
          "Nauru",
          "Nepal",
          "Netherlands",
          "New Zealand",
          "Nicaragua",
          "Niger",
          "Nigeria",
          "Norway",
          "Oman",
          "Pakistan",
          "Palau",
          "Panama",
          "Papua New Guinea",
          "Paraguay",
          "Peru",
          "Philippines",
          "Poland",
          "Portugal",
          "Qatar",
          "Romania",
          "Russian Federation",
          "Rwanda",
          "St Kitts and Nevis",
          "St Lucia",
          "Saint Vincent and the Grenadines",
          "Samoa",
          "San Marino",
          "Sao Tome and Principe",
          "Saudi Arabia",
          "Senegal",
          "Serbia",
          "Seychelles",
          "Sierra Leone",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "Solomon Islands",
          "Somalia",
          "South Africa",
          "South Sudan",
          "Spain",
          "Sri Lanka",
          "Sudan",
          "Suriname",
          "Swaziland",
          "Sweden",
          "Switzerland",
          "Syria",
          "Taiwan",
          "Tajikistan",
          "Tanzania",
          "Thailand",
          "Togo",
          "Tonga",
          "Trinidad and Tobago",
          "Tunisia",
          "Turkey",
          "Turkmenistan",
          "Tuvalu",
          "Uganda",
          "Ukraine",
          "United Arab Emirates",
          "United Kingdom",
          "United States",
          "Uruguay",
          "Uzbekistan",
          "Vanuatu",
          "Vatican City",
          "Venezuela",
          "Vietnam",
          "Yemen",
          "Zambia",
          "Zimbabwe",
        ],
      },
      {
        name: "sports",
        words: [
          "American Football",
          "Archery",
          "Artistic Swimming",
          "Athletics",
          "Badminton",
          "Baseball",
          "Basketball",
          "Bowls",
          "Boxing",
          "Canoeing",
          "Cricket",
          "Curling",
          "Cycling",
          "Darts",
          "Diving",
          "Equestrian",
          "Fencing",
          "Football",
          "Golf",
          "Gymnastics",
          "Handball",
          "Hockey",
          "Horse Racing",
          "Ice Hockey",
          "Judo",
          "Karate",
          "Mixed Martial Arts",
          "Netball",
          "Rowing",
          "Rugby",
          "Sailing",
          "Shooting",
          "Skateboarding",
          "Snooker",
          "Softball",
          "Squash",
          "Surfing",
          "Swimming",
          "Table Tennis",
          "Taekwondo",
          "Tennis",
          "Triathlon",
          "Volleyball",
          "Water Polo",
          "Weightlifting",
          "Wrestling",
        ],
      },
      {
        name: "capitals",
        words: [
          "Kabul",
          "Tirana",
          "Algiers",
          "Andorra la Vella",
          "Luanda",
          "Saint Johns",
          "Buenos Aires",
          "Yerevan",
          "Canberra",
          "Vienna",
          "Baku",
          "Nassau",
          "Manama",
          "Dhaka",
          "Bridgetown",
          "Minsk",
          "Brussels",
          "Belmopan",
          "Porto Novo",
          "Thimphu",
          "Sucre",
          "Sarajevo",
          "Gaborone",
          "Brasilia",
          "Bandar Seri Begawan",
          "Sofia",
          "Ouagadougou",
          "Gitega",
          "Praia",
          "Phnom Penh",
          "Yaounde",
          "Ottawa",
          "Bangui",
          "Ndjamena",
          "Santiago",
          "Beijing",
          "Bogota",
          "Moroni",
          "Kinshasa",
          "Brazzaville",
          "San Jose",
          "Yamoussoukro",
          "Zagreb",
          "Havana",
          "Nicosia",
          "Prague",
          "Copenhagen",
          "Djibouti",
          "Roseau",
          "Santo Domingo",
          "Quito",
          "Cairo",
          "San Salvador",
          "Malabo",
          "Asmara",
          "Tallinn",
          "Mbabane",
          "Addis Ababa",
          "Suva",
          "Helsinki",
          "Paris",
          "Libreville",
          "Banjul",
          "Tbilisi",
          "Berlin",
          "Accra",
          "Athens",
          "Saint Georges",
          "Guatemala City",
          "Conakry",
          "Bissau",
          "Georgetown",
          "Port au Prince",
          "Tegucigalpa",
          "Budapest",
          "Reykjavik",
          "New Delhi",
          "Jakarta",
          "Tehran",
          "Baghdad",
          "Dublin",
          "Jerusalem",
          "Rome",
          "Kingston",
          "Tokyo",
          "Amman",
          "Nur Sultan",
          "Nairobi",
          "South Tarawa",
          "Pristina",
          "Kuwait City",
          "Bishkek",
          "Vientiane",
          "Riga",
          "Beirut",
          "Maseru",
          "Monrovia",
          "Tripoli",
          "Vaduz",
          "Vilnius",
          "Luxembourg",
          "Antananarivo",
          "Lilongwe",
          "Kuala Lumpur",
          "Male",
          "Bamako",
          "Valletta",
          "Majuro",
          "Nouakchott",
          "Port Louis",
          "Mexico City",
          "Palikir",
          "Chisinau",
          "Monaco",
          "Ulaanbaatar",
          "Podgorica",
          "Rabat",
          "Maputo",
          "Nay Pyi Taw",
          "Windhoek",
          "Kathmandu",
          "Amsterdam",
          "Wellington",
          "Managua",
          "Niamey",
          "Abuja",
          "Pyongyang",
          "Skopje",
          "Oslo",
          "Muscat",
          "Islamabad",
          "Ngerulmud",
          "East Jerusalem",
          "Panama City",
          "Port Moresby",
          "Asuncion",
          "Lima",
          "Manila",
          "Warsaw",
          "Lisbon",
          "Doha",
          "Bucharest",
          "Moscow",
          "Kigali",
          "Basseterre",
          "Castries",
          "Kingstown",
          "Apia",
          "San Marino",
          "Sao Tome",
          "Riyadh",
          "Dakar",
          "Belgrade",
          "Victoria",
          "Freetown",
          "Singapore",
          "Bratislava",
          "Ljubljana",
          "Honiara",
          "Mogadishu",
          "Bloemfontein",
          "Cape Town",
          "Pretoria",
          "Seoul",
          "Juba",
          "Madrid",
          "Colombo",
          "Khartoum",
          "Paramaribo",
          "Stockholm",
          "Bern",
          "Damascus",
          "Dushanbe",
          "Dodoma",
          "Bangkok",
          "Dili",
          "Lome",
          "Nuku Alofa",
          "Port of Spain",
          "Tunis",
          "Ankara",
          "Ashgabat",
          "Funafuti",
          "Kampala",
          "Kiev",
          "Abu Dhabi",
          "London",
          "Washington DC",
          "Montevideo",
          "Tashkent",
          "Port Vila",
          "Vatican City",
          "Caracas",
          "Hanoi",
          "Sanaa",
          "Lusaka",
          "Harare",
        ],
      },
    ],
  });

  const user = await newUser.save();

  res.send({
    _id: user._id,
    name: user.name,
    username: user.username,
    email: user.email,
    dictionary: user.dictionary,
    categories: user.categories,
    createdAt: user.createdAt,
    token: generateToken(user),
  });
});

//Login
userRouter.post("/login", async (req, res) => {
  const user = await User.findOne({ username: req.body.username });

  if (user) {
    if (bcrypt.compareSync(req.body.password, user.password)) {
      res.send({
        _id: user._id,
        name: user.name,
        email: user.email,
        username: user.username,
        createdAt: user.createdAt,
        token: generateToken(user),
      });
    } else {
      return res.status(401).send({ msg: "Invalid credentials" });
    }
  } else {
    return res.status(401).send({ msg: "Invalid credentials" });
  }
});

//Get User Account
userRouter.get("/account/:username", protect, async (req, res) => {
  const user = await User.findOne({ username: req.params.username });
  const myDictionary = user.dictionary;
  const activeSince = user.createdAt;
  res.json({
    user,
    myDictionary,
    activeSince,
  });
});

//Edit User Account Details
userRouter.post("/edit-account", async (req, res) => {
  const user = await User.findOneAndUpdate(
    { username: req.body.username },
    {
      username: req.body.newUsername,
      email: req.body.newEmail,
    },
    {
      new: true,
    }
  );
  res.send({
    _id: user._id,
    name: user.name,
    email: user.email,
    username: user.username,
    createdAt: user.createdAt,
    token: generateToken(user),
  });
});

userRouter.post("/delete-account", async (req, res) => {
  const user = await User.findOneAndDelete({ username: req.body.username });
  const users = await User.find();
  res.json(users);
});

module.exports = userRouter;
